### ISSUE TITLE
Drop-table

### ISSUE THREAD

**Issue by nixianjun6** [nixianjun6/miniob#1]
删除表。清除表相关的资源。
注意：要删除所有与表关联的数据，不仅仅是在create table时创建的资源，还包括索引等数据。

**Comment by nixianjun6** [comment]
1

**Comment by nixianjun6** [comment]
撤销

**Comment by Cheney-He** [comment]
1

**Comment by Cheney-He** [comment]
解决办法：
1.在sql处理函数里加入处理drop table的case
2.删除table文件，data文件和索引，如果有的话
3.在default handler里面加入drop_table的接口，然后在table目录下加入删除相应资源的接口
